import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'UserList.dart';

class GetData extends StatefulWidget {
  const GetData({Key? key}) : super(key: key);

  @override
  State<GetData> createState() => _GetDataState();
}

class _GetDataState extends State<GetData> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'getData',
      theme: ThemeData(
        brightness: Brightness.dark,
      ),
      debugShowCheckedModeBanner: false,
      home: const Data(),
    );
  }
}

var stringResponse;
var mapResponse;
var dataResponse;

class Data extends StatefulWidget {
  const Data({Key? key}) : super(key: key);

  @override
  State<Data> createState() => _DataState();
}

class _DataState extends State<Data> {
  Future<Autogenerated> fetchUsers(String page) async {
    final response =
        await http.get(Uri.parse('https://reqres.in/api/users?page=$page'));
    if (response.statusCode == 200) {
      return Autogenerated.fromJson(jsonDecode(response.body));
    } else {
      throw Exception('Failed to load user list');
    }
  }

  @override
  void initState() {
    super.initState();

    fetchUsers("1").then((value) {
      print(value);
      setState(() {
        dataResponse = value;
      });
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: const Text('Fetch Data'),
        ),
        body: Center(
          child: ListView.builder(
              itemCount: dataResponse?.data?.length,
              itemBuilder: (BuildContext ctxt, int index) {
                return Card(
                    child: Row(
                  children: [
                    Image.network(dataResponse!.data![index].avatar!),
                    Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(
                          dataResponse!.data![index].firstName!,
                          style: const TextStyle(fontSize: 30),
                        ),
                        Text(
                          dataResponse!.data![index].lastName!,
                          style: const TextStyle(fontSize: 30),
                        )
                      ],
                    ),
                  ],
                ));
              }),
        ));
  }
}
